
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    environment:
    - ITEMS_DB=/data/items.db
    - REDIS_URL=redis://redis:6379/0
    volumes:
    - dbdata:/data
    depends_on:
    - redis


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.celery_app.celery", "worker", "--loglevel=info"]
    environment:
    - REDIS_URL=redis://redis:6379/0
    depends_on:
    - redis


  redis:
    image: redis:7-alpine
    ports:
    - "6379:6379"


volumes:
  dbdata: