---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items-api
  template:
    metadata:
      labels:
        app: items-api
    spec:
      containers:
        - name: api
          image: items-api:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ITEMS_DB
              value: /data/items.db
            - name: REDIS_URL
              value: redis://redis:6379/0
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: items-api
spec:
  selector:
    app: items-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items-worker
  template:
    metadata:
      labels:
        app: items-worker
    spec:
      containers:
        - name: worker
          image: items-api:latest
          imagePullPolicy: IfNotPresent
          command: ["celery", "-A", "app.celery_app.celery", "worker", "--loglevel=info"]
          env:
            - name: REDIS_URL
              value: redis://redis:6379/0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
